### ISSUE TITLE
Grainstation-C "template files" vs AKAI "presets"

### ISSUE THREAD

**Issue by jeremypbushnell** [chronopolis5k/Grainstation-C#6]
This is perhaps not an issue so much as it is a novice question (I am new to Csound and still something of a novice with MIDI in general). The Grainstation-C looks like a wonderful tool and I'm interested in using it with the AKAI MIDImixl. The AKAI MIDImix has a nearly identical interface and its template editor can open presets but it lacks the capacity to open sysex files. I've been trying to transfer them over via Sysex Librarian but it's difficult to tell whether that is having an effect (in any case, I'm not getting any sound out of the system). Is there a way to enter the template directly into an editor interface and save it as a preset (as an incidental note, the the AKAI MIDImix uses what looks like a proprietary filetype for its presets (they are listed as "MIDIMix Editor files"))?

**Comment by micah-frank-studio** [comment]
Hi Jeremy,

The only way might be to enter it manually. I am not familiar with the MIDImix. However, it shouldn't be too difficult to do it manually - just a few minutes of tedium ;) 

All of the CC values are indicated in the readme file.
